# This workflow is triggered when a PR is closed. It does the following:
#  - Check that the PR was merged (if not we can ignore)
#  - Check that the PR has the 'autorelease' label (if not we can ignore)
#  - Creates a draft release 
on:
  pull_request:
    branches:
    - main
    types: [closed]

name: '[autorelease] PR merged'

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'autorelease')
    steps:
    - uses: actions/checkout@v3

    - name: Get release version
      id: get-release-version
      run: |
        # Head branch should be named autorelease/<version>
        if ! [[ "${{ github.event.pull_request.head.ref }}" =~ ^autorelease\/[A-Za-z0-9.+-]+$ ]]; then
          echo "Invalid branch"
          exit 1
        fi
        VERSION=$(echo "${{ github.event.pull_request.head.ref }}" | awk -F/ '{print $2}')
        echo "VERSION=$VERSION"
        echo "::set-output name=release-version::$VERSION"

    - name: Get release notes
      id: get-release-notes
      uses: release-flow/keep-a-changelog-action/get-release-notes@v1
      with:
        release-version: ${{ steps.get-release-version.outputs.release-version}}


    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.TAGRELEASEBOT_APP_ID }}
        private_key: ${{ secrets.TAGRELEASEBOT_APP_KEY }}

    - name: Create draft release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      with:
        tag_name: 'v${{ steps.get-release-version.outputs.release-version }}'
        release_name: 'Release ${{ steps.get-release-version.outputs.release-version }}'
        draft: true
        body: ${{ steps.get-release-notes.outputs.release-notes }}

    - name: Display instructions
      run: |
        echo "::notice title=Draft Release Prepared::Draft release ${{ steps.create_release.outputs.id }} has been prepared for you to approve: ${{ steps.create_release.outputs.html_url }}"
  