# Sample workflow that uses a manual trigger to demonstrate how to use the actions in this repo

name: 'Run sample actions'
on:
  workflow_dispatch:

jobs:
  start_maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: start
        name: Start maintenance window
        uses: ./start
        with:
          app-url: ${{ secrets.MAINTZ_FUNC_URL }}
          app-key: ${{ secrets.MAINTZ_FUNC_APP_KEY }}
          monitor-id: '63332000012700001' # Glider-Staging - our test monitor
          duration: 1 # 1 minute
    outputs:
      maintenance-id: ${{ steps.start.outputs.maintenance-id }}

  end_maintenance:
    runs-on: ubuntu-latest
    needs: ['start_maintenance']
    steps:
      - uses: actions/checkout@v3
      - name: End maintenance window
        uses: ./end
        with:
          app-url: ${{ secrets.MAINTZ_FUNC_URL }}
          app-key: ${{ secrets.MAINTZ_FUNC_APP_KEY }}
          maintenance-id: ${{ needs.start_maintenance.outputs.maintenance-id }}
