name: 'build-test'
on: # rebuild any PRs and main / release branch changes
  pull_request:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./main
        with:
          milliseconds: 1000
